{"timestamp":"2025-08-27T00:44:12.555874","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-27T00:44:12.556501","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/elasticsearch_hook.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-27T00:44:12.635555","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-27T00:44:12.684865","level":"info","event":"Connection Retrieved 'elasticsearch_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-27T00:44:13.212107","level":"info","event":"GET https://es01:9200/ [status:N/A duration:0.040s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-27T00:44:13.212278","level":"warning","event":"Node <Urllib3HttpNode(https://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-27T00:44:13.212334","level":"warning","event":"Retrying request after failure (attempt 0 of 3)","logger":"elastic_transport.transport","error_detail":[{"exc_type":"TlsError","exc_value":"TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLCertVerificationError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":96,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":45,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":790,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":969,"name":"_ssl_wrap_socket_and_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":480,"name":"ssl_wrap_socket"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":524,"name":"_ssl_wrap_socket_impl"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":455,"name":"wrap_socket"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1041,"name":"_create"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1319,"name":"do_handshake"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-27T00:44:13.256454","level":"info","event":"GET https://es01:9200/ [status:N/A duration:0.038s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-27T00:44:13.256595","level":"warning","event":"Node <Urllib3HttpNode(https://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-27T00:44:13.256673","level":"warning","event":"Retrying request after failure (attempt 1 of 3)","logger":"elastic_transport.transport","error_detail":[{"exc_type":"TlsError","exc_value":"TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLCertVerificationError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":96,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":45,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":790,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":969,"name":"_ssl_wrap_socket_and_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":480,"name":"ssl_wrap_socket"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":524,"name":"_ssl_wrap_socket_impl"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":455,"name":"wrap_socket"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1041,"name":"_create"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1319,"name":"do_handshake"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-27T00:44:13.317402","level":"info","event":"GET https://es01:9200/ [status:N/A duration:0.059s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-27T00:44:13.317582","level":"warning","event":"Node <Urllib3HttpNode(https://es01:9200)> has failed for 3 times in a row, putting on 4 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-27T00:44:13.317638","level":"warning","event":"Retrying request after failure (attempt 2 of 3)","logger":"elastic_transport.transport","error_detail":[{"exc_type":"TlsError","exc_value":"TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLCertVerificationError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":96,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":45,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":790,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":969,"name":"_ssl_wrap_socket_and_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":480,"name":"ssl_wrap_socket"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":524,"name":"_ssl_wrap_socket_impl"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":455,"name":"wrap_socket"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1041,"name":"_create"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1319,"name":"do_handshake"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-27T00:44:13.390089","level":"info","event":"GET https://es01:9200/ [status:N/A duration:0.072s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-27T00:44:13.390231","level":"warning","event":"Node <Urllib3HttpNode(https://es01:9200)> has failed for 4 times in a row, putting on 8 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-27T00:44:13.394447","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TlsError","exc_value":"TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/elasticsearch_hook.py","lineno":16,"name":"do_some_stuff"},{"filename":"/opt/airflow/plugins/elasticsearch_plugin/hooks/elasticsearch_hook.py","lineno":47,"name":"info"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/utils.py","lineno":452,"name":"wrapped"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/__init__.py","lineno":3065,"name":"info"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/_base.py","lineno":271,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/_base.py","lineno":315,"name":"_perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLCertVerificationError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":96,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_urllib3_chain_certs.py","lineno":45,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":790,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":969,"name":"_ssl_wrap_socket_and_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":480,"name":"ssl_wrap_socket"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":524,"name":"_ssl_wrap_socket_impl"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":455,"name":"wrap_socket"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1041,"name":"_create"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1319,"name":"do_handshake"}],"is_group":false,"exceptions":[]}]}
